# Generated by Django 6.0.3 on 2026-03-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('ecocash', 'EcoCash'), ('physical', 'Physical Cash / Receipt')], default='bank', max_length=15),
        ),
    ]
