# Generated by Django 6.0.3 on 2026-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': '📊 Overview Dashboard',
                'verbose_name_plural': '📊 Overview Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracker.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
