# Generated by Django 6.0.3 on 2026-03-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dashboard_payment_receipt_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
